### ISSUE TITLE
Qt5

### ISSUE THREAD

**Issue by ShalokShalom** [Shinmera/qtools#27]
Since CommonQt is still on Qt4: is this project too?

P.S: Very nice README, by the way ^-^

**Comment by Shinmera** [comment]
Yes.

**Comment by C-Entropy** [comment]
> Yes.

Is there any plans for qt5?Is there anything We can do for help?

**Comment by phoe** [comment]
> Is there anything We can do for help?

Yes - create Qt5 bindings for Common Lisp.

**Comment by C-Entropy** [comment]
Alright, I will try to find some guide and give it a try. I will do my best, but I'm new here, so don't expect too much.

**Comment by phoe** [comment]
It is a very non-trivial task. Basically, you'll want to create a CommonQt equivalent that does *not* bind against Qt4 but against Qt5 instead. And, since you can't use Smoke to bind against Qt5, this means either designing the idea of how to bind against Qt5 from scratch or taking a look at how some other, already existing Qt5 bindings, do it, and copying this behavior into the Lisp world.

**Comment by C-Entropy** [comment]
I have found a python one and wondering if it is possible to port it.

**Comment by Shinmera** [comment]
Someone recently sent me an email apparently successfully using Qt5. I don't have time to investigate it myself, though. I prompted them to post an issue about it on GitHub, but they have not done so since.

So, here's the email content, in public interest:

> Hi Nicolas, I am sending you the patch for commonqt5 and instructions to build on Ubuntu
> 
>  mate 20.04, as well as smokegen, smokeqt5 and Qt 5.15.0 binaries, built on Win 10 and 
> 
> tested in a Win 7 VM.
> 
> In win 7:
> 
> Put the path where you have commonqtdll.
> 
> Errors when running commonqt tutorial  Win 7:
> 
> qt.qpa.plugin: Could not find the Qt platform plugin "windows" in "" This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> set QT_QPA_PLATFORM_PLUGIN_PATH=dir\commonqtdll
> 
> QWindowsEGLStaticContext::create: Could not initialize EGL display: error 0x3001 QWindowsEGLStaticContext::create: When using ANGLE, check if d3dcompiler_4x.dll is available
> 
> set QT_OPENGL=desktop
> 
> Link  smokegenerador:
> 
> https://drive.google.com/file/d/11G2R31U9GvyNbJ8OspzaajESmgFiF08F/view?usp=sharing
> 
> Link  commonqtdll:
> 
> https://drive.google.com/file/d/1XgZgnU2VVV74h8TLnljjv4siR_Fh8sOd/view?usp=sharing
> 
> confirm received.
> 
> Enjoy it.

The following files were attached to the mail:
[instructions.zip](https://filebox.tymoon.eu//file/TWpBek1RPT0=)
[commonqt5.patch](https://filebox.tymoon.eu//file/TWpBek1nPT0=)

**Comment by mcristg** [comment]
The commonQt5 version can be obtained from https://github.com/mcristg/commonqt
git clone -b commonqt5 https://github.com/mcristg/commonqt

**Comment by vindarel** [comment]
@mcristg That seems phenomenal. Would you add a README and/or a reproducible example?

**Comment by Shinmera** [comment]
Fwiw there's some official qt5 discussion here: https://github.com/commonqt/commonqt/pull/49

**Comment by mcristg** [comment]
@Shinmera, sorry for the noise.

**Comment by Shinmera** [comment]
No worries!

**Comment by phoe** [comment]
Y'all thinking about Qt5 and [in meanwhile](https://www.qt.io/blog/qt-6.0-released)...

![Zrzut ekranu z 2020-12-08 14-51-41](https://user-images.githubusercontent.com/15045546/101492157-e5368380-3964-11eb-906f-e754e7c23162.png)

**Comment by phoe** [comment]
https://github.com/commonqt/commonqt5
